Repository Conflux-Chain/conflux-rust, pull requests merged in 2020-10, with the labels that each got.

#1872 Adjust POW DAG size
  core/src/pow/shared.rs
Labels: spec breaking

#1878 Tweak the connection between the compute and the memory for pow
  core/src/pow/compute.rs
Labels: spec breaking

#1879 Remove quotation marks from cfx_call revert message
  client/src/rpc/error_codes.rs
  tests/contracts/revert_message.abi
  tests/contracts/revert_message.dat
  tests/contracts/revert_message.sol
  tests/rpc/test_contract.py
Labels: database/interface breaking

#1887 Let AdminContract regard sender (other than original sender) as requester
  core/src/executive/internal_contract/impls/admin.rs
  core/src/state/account_entry.rs
  core/src/state/mod.rs
Labels: spec breaking

#1893 Forbid compile on big-endian platform
  core/src/pow/mod.rs
Labels: backward compatible

#1902 Improve light node sync and logging
  Cargo.lock
  client/src/configuration.rs
  client/src/light/mod.rs
  core/parameters/src/lib.rs
  core/src/light_protocol/config.rs
  core/src/light_protocol/handler/mod.rs
  core/src/light_protocol/handler/sync/block_txs.rs
  core/src/light_protocol/handler/sync/blooms.rs
  core/src/light_protocol/handler/sync/common/priority_queue.rs
  core/src/light_protocol/handler/sync/common/sync_manager.rs
  core/src/light_protocol/handler/sync/epochs.rs
  core/src/light_protocol/handler/sync/headers.rs
  core/src/light_protocol/handler/sync/receipts.rs
  core/src/light_protocol/handler/sync/state_entries.rs
  core/src/light_protocol/handler/sync/state_roots.rs
  core/src/light_protocol/handler/sync/storage_roots.rs
  core/src/light_protocol/handler/sync/tx_infos.rs
  core/src/light_protocol/handler/sync/txs.rs
  core/src/light_protocol/handler/sync/witnesses.rs
  core/src/light_protocol/mod.rs
  core/src/light_protocol/provider.rs
  core/src/light_protocol/query_service.rs
  run/default.toml
Labels: backward compatible

#1914 Return estimated gas_limit in rpc.
  client/src/rpc/impls/cfx.rs
  client/src/rpc/types/call_request.rs
Labels: docs inconsistent

#1933 Light node RPC fixes
  client/src/light/mod.rs
  client/src/rpc/error_codes.rs
  client/src/rpc/impls.rs
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/common.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
  core/src/block_data_manager/mod.rs
  core/src/light_protocol/query_service.rs
  tests/light/rpc_test.py
Labels: backward compatible

#1943 Make cfx_getTransactionReceipt on light nodes return null on timeout
  client/src/rpc/impls/light.rs
  core/src/light_protocol/mod.rs
Labels: backward compatible
