Repository Conflux-Chain/conflux-rust, pull requests merged in 2020-07, with the labels that each got.

#1618 Add cfx_clientVersion rpc and CHANGELOG updates.
  CHANGELOG.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/common.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
Labels: backward compatible

#1663 Fix some random test failure.
  tests/full_node_tests/remove_old_eras_test.py
  tests/full_node_tests/sync_checkpoint_test.py
Labels: backward compatible

#1659 Check addr type in tx exectution
  CHANGELOG.md
  client/src/rpc/impls/cfx.rs
  core/src/consensus/consensus_inner/consensus_executor.rs
  core/src/evm/interpreter/mod.rs
  core/src/executive/context.rs
  core/src/executive/executed.rs
  core/src/executive/executive.rs
  core/src/vm/error.rs
  core/src/vm/tests.rs
Labels: spec synced

#1651 Reimplement contract call stack maintainance for reentrancy check.
  core/src/executive/context.rs
  core/src/executive/executive.rs
  core/src/state/mod.rs
  core/src/state/substate.rs
Labels: spec breaking

#1669 Allow transfer() in reentrancy check.
  CHANGELOG.md
  core/src/evm/interpreter/mod.rs
  core/src/executive/context.rs
  core/src/executive/executive.rs
  core/src/state/substate.rs
  core/src/vm/context.rs
  core/src/vm/error.rs
  core/src/vm/tests.rs
  tests/reentrancy_test.py
Labels: spec synced

#1687 Bump version to 1.0.0
  Cargo.toml
  client/Cargo.toml
  core/Cargo.toml
Labels: backward compatible

#1688 Split changelog to major versions
  CODEOWNERS
  changelogs/CHANGELOG-0.6.x.md
  changelogs/CHANGELOG-1.0.x.md
  changelogs/CHANGELOG-pre-0.6.md
Labels: backward compatible

#1686 Use MPT proofs on light nodes for transactions and receipts
  Cargo.lock
  core/src/light_protocol/handler/mod.rs
  core/src/light_protocol/handler/sync/tx_infos.rs
  core/src/light_protocol/message/protocol.rs
  core/src/light_protocol/provider.rs
  core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs
  core/src/storage/impls/merkle_patricia_trie/simple_mpt.rs
  core/src/storage/impls/merkle_patricia_trie/trie_proof.rs
  core/src/storage/tests/snapshot.rs
  core/src/verification.rs
  tests/light/tx_relay_test.py
Labels: backward compatible

#1679 Prevent race between state root and state entry request in light node
  core/src/light_protocol/handler/sync/state_entries.rs
  core/src/light_protocol/message/protocol.rs
  core/src/light_protocol/provider.rs
  core/src/light_protocol/query_service.rs
Labels: backward compatible

#1698 Check mining address prefix and panic with a proper message
  client/src/common/mod.rs
Labels: backward compatible

#1699 Improve log message levels
  blockgen/stratum/src/lib.rs
  client/src/rpc/impls/cfx.rs
Labels: backward compatible

#1703 Add metrics for node statistics.
  core/src/consensus/mod.rs
  core/src/statistics/mod.rs
Labels: backward compatible, enhancement

#1697 Make sure accounts created through CLI are re-read on running node
  accounts/cfxstore/src/cfxstore.rs
  changelogs/CHANGELOG-1.0.x.md
  client/src/accounts.rs
  client/src/common/mod.rs
  client/src/configuration.rs
  run/default.toml
  src/cli.yaml
  src/command/account.rs
Labels: backward compatible, enhancement

#1700 Remove intermediate_padding from StateProof
  core/src/light_protocol/error.rs
  core/src/light_protocol/handler/mod.rs
  core/src/light_protocol/handler/sync/state_entries.rs
  core/src/light_protocol/handler/sync/state_roots.rs
  core/src/light_protocol/handler/sync/storage_roots.rs
  core/src/light_protocol/message/mod.rs
  core/src/light_protocol/message/protocol.rs
  core/src/light_protocol/provider.rs
  core/src/storage/impls/state.rs
  core/src/storage/impls/state_proof.rs
  core/src/storage/tests/proofs.rs
Labels: backward compatible

#1711 Downgrade a warning to log
  core/src/state/mod.rs
Labels: backward compatible

#1705 Improve light node provider error handling
  core/src/light_protocol/common/mod.rs
  core/src/light_protocol/error.rs
  core/src/light_protocol/provider.rs
  core/src/parameters.rs
Labels: backward compatible, enhancement

#1708 Upgrade rust toolchain to 1.45.0.
  accounts/cfxstore/src/cfxstore.rs
  core/src/consensus/consensus_inner/consensus_new_block_handler.rs
  core/src/evm/interpreter/memory.rs
  core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs
  core/src/storage/impls/storage_db/kvdb_rocksdb.rs
  core/src/storage/impls/storage_manager/storage_manager.rs
  core/src/storage/utils/mod.rs
  core/src/sync/synchronization_graph.rs
  core/src/transaction_pool/impls/node.rs
  core/src/transaction_pool/nonce_pool.rs
  network/src/service.rs
  rust-toolchain
  src/test.rs
  util/io/src/worker.rs
  util/link-cut-tree/src/lct.rs
Labels: backward compatible

#1718 Only delete block bodies of blocks in the past of a checkpoint.
  core/src/consensus/consensus_inner/consensus_new_block_handler.rs
  core/src/consensus/consensus_inner/mod.rs
  tests/full_node_tests/remove_old_eras_test.py
Labels: backward compatible

#1720 Delay deleting block bodies for one checkpoint.
  core/src/consensus/consensus_inner/consensus_new_block_handler.rs
  core/src/consensus/consensus_inner/mod.rs
Labels: backward compatible

#1709 Update block reward according to CIP-10
  core/src/consensus/consensus_inner/consensus_executor.rs
  core/src/parameters.rs
  tests/rpc/test_get_block_reward_info.py
  tests/secondary_reward_test.py
Labels: spec breaking

#1665 CIP 8-Move all the collateral settlement to the end of execution
  changelogs/CHANGELOG-1.0.x.md
  core/src/executive/context.rs
  core/src/executive/executive.rs
  core/src/executive/executive_tests.rs
  core/src/executive/internal_contract/impls/admin.rs
  core/src/state/account_entry.rs
  core/src/state/account_entry_tests.rs
  core/src/state/mod.rs
  core/src/state/state_tests.rs
  core/src/state/substate.rs
Labels: spec breaking

#1722 Claim the value can never be `Apparent` in creation
  core/src/executive/executive.rs
Labels: backward compatible

#1715 separate Heartbeat message from Status
  core/src/sync/message/heartbeat.rs
  core/src/sync/message/message.rs
  core/src/sync/message/mod.rs
  core/src/sync/message/snapshot_chunk_request.rs
  core/src/sync/message/snapshot_chunk_response.rs
  core/src/sync/message/snapshot_manifest_request.rs
  core/src/sync/message/snapshot_manifest_response.rs
  core/src/sync/message/state_sync_candidate_request.rs
  core/src/sync/message/state_sync_candidate_response.rs
  core/src/sync/message/status.rs
  core/src/sync/message/transactions.rs
  core/src/sync/mod.rs
  core/src/sync/synchronization_protocol_handler.rs
  core/src/sync/synchronization_state.rs
  tests/conflux/messages.py
  tests/test_framework/mininode.py
Labels: backward compatible
