Repository Conflux-Chain/conflux-rust, pull requests merged in 2020-09, with the labels that each got.

#1807 Add timeout for influxdb report.
  util/metrics/src/report_influxdb.rs
Labels: backward compatible, bug

#1808 Reject unknown filter fields in cfx_getLogs
  client/src/rpc/types/filter.rs
  tests/rpc/test_get_logs.py
Labels: backward compatible

#1810 Fix bug where tx pool isn't notified by state execution.
  core/src/state/mod.rs
Labels: bug

#1813 Use State in tx pool for structured data access
  core/src/state/mod.rs
  core/src/transaction_pool/account_cache.rs
  core/src/transaction_pool/mod.rs
  core/src/transaction_pool/transaction_pool_inner.rs
Labels: backward compatible

#1811 Add a field gas_used to rpc Block type
  changelogs/CHANGELOG-0.6.x.md
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/types/block.rs
Labels: database/interface breaking

#1833 Fix issue #1830.
  core/src/consensus/consensus_inner/mod.rs
Labels: backward compatible

#1836 Add timer for getLogs and sendRawTransaction.
  Cargo.lock
  client/Cargo.toml
  client/src/rpc/impls/cfx.rs
  util/metrics/src/lib.rs
  util/metrics/src/timer.rs
Labels: backward compatible

#1834 Only load the header in get_best_info_with_packed_transactions.
  core/src/transaction_pool/mod.rs
Labels: backward compatible

#1840 Tx err msg into receipts
  core/src/consensus/consensus_inner/consensus_executor.rs
  core/src/genesis.rs
  core/src/vm/error.rs
  primitives/src/block_header.rs
  primitives/src/receipt.rs
Labels: database/interface breaking

#1797 Add special tombstone value to storage root
  Cargo.lock
  changelogs/CHANGELOG-0.6.x.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
  client/src/rpc/types.rs
  client/src/rpc/types/storage_root.rs
  core/src/light_protocol/common/ledger_info.rs
  core/src/light_protocol/handler/sync/storage_roots.rs
  core/src/light_protocol/message/protocol.rs
  core/src/light_protocol/query_service.rs
  core/statedb/src/lib.rs
  core/storage/src/impls/delta_mpt/cow_node_ref.rs
  core/storage/src/impls/delta_mpt/mem_optimized_trie_node.rs
  core/storage/src/impls/delta_mpt/subtrie_visitor.rs
  core/storage/src/impls/merkle_patricia_trie/mod.rs
  core/storage/src/impls/merkle_patricia_trie/mpt_cursor.rs
  core/storage/src/impls/merkle_patricia_trie/mpt_value.rs
  core/storage/src/impls/merkle_patricia_trie/trie_node.rs
  core/storage/src/impls/merkle_patricia_trie/trie_proof.rs
  core/storage/src/impls/node_merkle_proof.rs
  core/storage/src/impls/snapshot_sync/offer/mpt_slicer.rs
  core/storage/src/impls/state.rs
  core/storage/src/impls/state_proof.rs
  core/storage/src/lib.rs
  core/storage/src/tests/proofs.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/state_root.rs
  primitives/src/storage.rs
  tests/contracts/simple_storage.abi
  tests/contracts/simple_storage.dat
  tests/contracts/simple_storage.sol
  tests/light/get_storage_root_test.py
  tests/storage_root_test.py
  tests/test_framework/util.py
Labels: database/interface breaking, docs inconsistent

#1841 Tx err msg into RpcReceipts
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/types/block.rs
  client/src/rpc/types/receipt.rs
  core/src/consensus/consensus_inner/mod.rs
  core/src/consensus/consensus_trait.rs
  core/src/consensus/mod.rs
  core/src/light_protocol/handler/sync/tx_infos.rs
  core/src/light_protocol/mod.rs
  core/src/light_protocol/provider.rs
  core/src/light_protocol/query_service.rs
Labels: database/interface breaking

#1843 Remove whitelist keys at contract deletion.
  changelogs/CHANGELOG-1.0.x.md
  core/src/executive/executive.rs
  core/src/state/mod.rs
Labels: spec breaking

#1858 Add string and bytes to ABI implementation
  util/solidity-abi/src/bytes.rs
  util/solidity-abi/src/lib.rs
  util/solidity-abi/src/string.rs
  util/solidity-abi/src/tests.rs
Labels: backward compatible

#1867 Enlarge mpt node buffer size to 5 million.
  core/storage/src/impls/delta_mpt/node_memory_manager.rs
Labels: backward compatible

#1866 Set snapshot_epoch_count to 2000.
  changelogs/CHANGELOG-1.0.x.md
  core/parameters/src/lib.rs
Labels: spec breaking

#1853 Add a new contract address scheme which use block_number in contract address calculation.
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/types/block.rs
  client/src/rpc/types/receipt.rs
  core/src/block_data_manager/block_data_types.rs
  core/src/consensus/consensus_inner/consensus_executor.rs
  core/src/consensus/consensus_inner/mod.rs
  core/src/consensus/consensus_trait.rs
  core/src/consensus/mod.rs
  core/src/executive/context.rs
  core/src/executive/executive.rs
  core/src/executive/executive_tests.rs
  core/src/genesis.rs
  core/src/light_protocol/query_service.rs
  core/src/vm/context.rs
  primitives/src/block_header.rs
  primitives/src/receipt.rs
  transactiongen/src/lib.rs
Labels: backward compatible
