Repository Conflux-Chain/conflux-rust, pull requests merged in 2020-08, with the labels that each got.

#1738 Add metrics to monitor invalid state root.
  core/src/consensus/consensus_inner/mod.rs
Labels: backward compatible

#1734 update octopus algorithm
  core/src/pow/compute.rs
  core/src/pow/mod.rs
  core/src/pow/shared.rs
Labels: spec breaking

#1742 changed `POW_MOD` value
  core/src/pow/shared.rs
Labels: spec breaking

#1695 Fix SimpleMpt key padding
  changelogs/CHANGELOG-1.0.x.md
  core/src/storage/impls/merkle_patricia_trie/simple_mpt.rs
Labels: bug, spec breaking

#1717 Use big-endian MPT keys
  changelogs/CHANGELOG-1.0.x.md
  core/src/storage/impls/merkle_patricia_trie/simple_mpt.rs
Labels: spec breaking

#1706 Start mining when `mining_author` is set.
  blockgen/src/lib.rs
  changelogs/CHANGELOG-0.6.x.md
  changelogs/CHANGELOG-1.0.x.md
  client/src/common/mod.rs
  client/src/configuration.rs
  client/src/tests/blockgen_tests.rs
  core/src/pow/mod.rs
  core/src/sync/utils.rs
  network/src/node_table.rs
  run/default.toml
  tests/conflux/config.py
  tests/secondary_reward_test.py
Labels: database/interface breaking, docs inconsistent

#1772 Fix #1760
  client/src/rpc/impls/common.rs
Labels: backward compatible

#1768 Add optional parameter `get_logs_filter_max_epoch_gap`.
  client/src/configuration.rs
  core/src/consensus/mod.rs
  core/src/sync/utils.rs
  primitives/src/filter.rs
  run/default.toml
  src/cli.yaml
  tests/log_filtering_test.py
Labels: backward compatible

#1770 Change version to 1.45.0 in README
  README.md
Labels: backward compatible

#1781 Add tx-pool related debug rpc
  blockgen/src/lib.rs
  changelogs/CHANGELOG-0.6.x.md
  client/Cargo.toml
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/common.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/debug.rs
  client/src/rpc/types.rs
  client/src/rpc/types/transaction.rs
  core/src/transaction_pool/mod.rs
  core/src/transaction_pool/nonce_pool.rs
  core/src/transaction_pool/transaction_pool_inner.rs
  src/cli.yaml
Labels: docs inconsistent

#1730 Add revised light node blame verification
  client/src/archive/mod.rs
  client/src/common/mod.rs
  client/src/full/mod.rs
  client/src/light/mod.rs
  core/parameters/src/lib.rs
  core/src/block_data_manager/block_data_types.rs
  core/src/block_data_manager/db_manager.rs
  core/src/block_data_manager/mod.rs
  core/src/cache_manager.rs
  core/src/channel.rs
  core/src/consensus/consensus_inner/blame_verifier.rs
  core/src/consensus/consensus_inner/consensus_new_block_handler.rs
  core/src/consensus/consensus_inner/mod.rs
  core/src/consensus/consensus_trait.rs
  core/src/consensus/mod.rs
  core/src/db.rs
  core/src/lib.rs
  core/src/light_protocol/common/ledger_info.rs
  core/src/light_protocol/error.rs
  core/src/light_protocol/handler/mod.rs
  core/src/light_protocol/handler/sync/blooms.rs
  core/src/light_protocol/handler/sync/common/priority_queue.rs
  core/src/light_protocol/handler/sync/common/sync_manager.rs
  core/src/light_protocol/handler/sync/receipts.rs
  core/src/light_protocol/handler/sync/state_roots.rs
  core/src/light_protocol/handler/sync/tx_infos.rs
  core/src/light_protocol/handler/sync/witnesses.rs
  core/src/light_protocol/message/mod.rs
  core/src/light_protocol/provider.rs
  core/src/light_protocol/query_service.rs
  core/src/node_type.rs
  core/src/sync/message/get_blocks.rs
  core/src/sync/message/status.rs
  core/src/sync/mod.rs
  core/src/sync/request_manager/mod.rs
  core/src/sync/request_manager/request_batcher.rs
  core/src/sync/request_manager/request_handler.rs
  core/src/sync/synchronization_graph.rs
  core/src/sync/synchronization_protocol_handler.rs
  core/src/sync/synchronization_service.rs
  core/src/sync/synchronization_state.rs
  core/src/sync/utils.rs
  core/storage/src/impls/storage_manager/storage_manager.rs
  tests/conflux/rpc.py
  tests/light/sync_test.py
  tests/light/tx_relay_test.py
Labels: backward compatible

#1799 Report metrics to influxdb in a random interval and only record reporting time when succeeded
  util/metrics/src/report.rs
  util/metrics/src/report_influxdb.rs
Labels: backward compatible, enhancement
