Repository Conflux-Chain/conflux-rust, pull requests merged in 2020-11, with the labels that each got.

#1946 Serve genesis block from local DB on light nodes
  core/src/light_protocol/query_service.rs
  tests/light/rpc_test.py
Labels: backward compatible

#1947 Add periodic heartbeats to the light protocol
  core/parameters/src/lib.rs
  core/src/light_protocol/handler/mod.rs
  core/src/light_protocol/handler/sync/epochs.rs
  core/src/light_protocol/handler/sync/headers.rs
  core/src/light_protocol/provider.rs
Labels: backward compatible

#1953 Light node cfx_gasPrice
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/common.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
  core/parameters/src/lib.rs
  core/src/light_protocol/query_service.rs
  tests/light/rpc_test.py
Labels: backward compatible

#1967 Return storage collateral and sponsor info in cfx_getTransactionReceipt
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/types/call_request.rs
  client/src/rpc/types/receipt.rs
  core/src/executive/executive.rs
  core/src/executive/executive_tests.rs
  primitives/src/receipt.rs
  tests/rpc/test_tx_receipt_by_hash.py
  tests/sponsored_tx_test.py
Labels: database/interface breaking, docs inconsistent

#1954 Light node cfx_getAccumulateInterestRate and cfx_getInterestRate
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
  core/src/light_protocol/query_service.rs
  core/statedb/src/lib.rs
  core/statedb/src/statedb_ext.rs
  tests/light/rpc_test.py
Labels: backward compatible

#1966 Update to the latest bootnodes.
  run/tethys.toml
Labels: backward compatible

#1987 Add cfx_getSupplyInfo.
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/impls/cfx.rs
  client/src/rpc/impls/light.rs
  client/src/rpc/traits/cfx.rs
  client/src/rpc/types.rs
  client/src/rpc/types/token_supply_info.rs
  tests/conflux/rpc.py
  tests/rpc/test_token_supply_info.py
Labels: docs inconsistent

#1991 Change the blame field returned from the newHeads pub-sub to hex
  changelogs/CHANGELOG-1.0.x.md
  client/src/rpc/types/block.rs
Labels: database/interface breaking, docs inconsistent
